repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    files: '\.yaml$'
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.21
  hooks:
  - id: helmlint
    files: 'templates/.*\.yaml'
