{{- if .Values.sst.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gtm-cloud-helm.fullname" . }}-sst
  labels:
    {{- include "gtm-cloud-helm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gtm-cloud-helm.fullname" . }}
  minReplicas: {{ .Values.sst.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sst.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.sst.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.sst.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.sst.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.sst.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
---
{{- if .Values.preview.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gtm-cloud-helm.fullname" . }}-preview
  labels:
    {{- include "gtm-cloud-helm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gtm-cloud-helm.fullname" . }}
  minReplicas: {{ .Values.preview.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.preview.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.preview.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.preview.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.preview.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.preview.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
