{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gtm-cloud-helm.serviceAccountName" . }}
  namespace: {{ include "gtm-cloud-helm.namespace" . }}
  labels:
    {{- include "gtm-cloud-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
